### ISSUE TITLE
TOKEN_INVALID response after a while 

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#14]
When I'm connected and did a get_device() everything works but after some idle time('not sure how long) and trying to use something else with the same myjd instance (like downloads.queryLinks) I'm getting the following responds:
"src":"MYJD"
403 TOKEN_INVALID

seems 'some' token expired ? the [old docs](https://docs.google.com/document/d/1IGeAwg8bQyaCTeTl_WyjLyBPh4NBOayO0_MAmvP5Mu4/edit) say to reconnect. 
tought something like this was a good idea
````
        if encrypted_response.status_code != 200:
            if 'TOKEN_INVALID' in encrypted_response.text and path != "/my/reconnect" and path != "/my/connect":
                response = self.reconnect()
                if response:
                    response = self.request_api(path, http_method, params, action, api)
                    return response
            else:
                  ...
````

but then I get a 403 AUTH_FAILED. =( so seems it cannot be solved without doing a connect() with email/pw again from outside myjdapi.

this also relates to issue #12 & #13

**Comment by neox387** [comment]
I saw the auth_fail with above code with it doing a reconnect on it's own not externally.

Tought it would make more sense to try and put it in there then always doing a reconnect() even when not needed from withing my program when it starts a new download since that could be a day in between.

**Comment by neox387** [comment]
well without the above reconnect section i'm still getting this :(
4 hours after the initial connection doing a connect again on same myjdapi.Myjdapi() results in:
SOURCE: MYJD
TYPE: AUTH_FAILED
REQUEST_URL: https://api.jdownloader.org/my/connect/my/connect?email=*&appkey=*&rid=*&signature=*

**Comment by mmarquezs** [comment]
Yeah I see that, it's a bug it only allows you to call connect() once. But reconnect() should work fine when you get TOKEN_INVALID .

**Comment by mmarquezs** [comment]
OK I could reproduce the AUTH_FAILED when using reconnect. It's simply because the token used to reconnect it's not valid anymore (regaintoken) , to be honest I thought it would last longer. 

When that happens the only thing you can do is to login again with mail and password as far as I can tell. But as it is now that fails because the only way you can call connect again is if you call disconnect but that get's you an AUTH_FAILED again ....

I will probably modify it so the **connect** function works even if a connection is already set.
