### ISSUE TITLE
Downloads.query_links

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#2]
Using development branch on python 2.7.11

Api interface not found error

Need to get download stats of a package actually but seems they have no info on what parameters that needs :/

Allso on link grabber. Add_links I can't get destination folder to work "C:\\test"  etc tried with different slashes

**Comment by mmarquezs** [comment]
Well... It took me a while to udnerstand what did you mean but i found it. The thing is that mainly I have been doing the linkgrabber part of the api, so the downloads part it wasn't even tested. 
First,  I saw the error in the "cleanup" function, it seems after my last commit I didn't test it, sorry for that.  It's fixed now. 
Second I fixed an error in request_api that crashed when showing the api errors. 
Third I changed the default params in downloads.query_links function to show all links by default.
Finally if you want to get info of a package in the downloads list you do something like this:
For example I want the speed , eta, and status of the package with UUID 1458565380967 in the dveice "TEST", after i have connected  I do this:

> jd.get_device("TEST").downloads.query_links([{"speed":True,"status":True,"eta":True,"packageUUIDs":[1458565380967]}])

And the output :

> [{u'name': u'Top 10 Portal Easter Eggs (&lng=en&kind=asr).srt',
  u'packageUUID': 1458565380967,
  u'speed': 915,
  u'status': u'Desc\xe0rrega',
  u'statusIconKey': u'kc.ae26dcaf8e0c02896c69ba8a1968637c',
  u'uuid': 1458565350119},
 {u'name': u'Top 10 Portal Easter Eggs (1080p).mp4',
  u'packageUUID': 1458565380967,
  u'speed': 0,
  u'status': u'Saltat - Falta FFmpeg\u2122',
  u'statusIconKey': u'kc.021c2b76a1e5849ab674b03a3eb573a1',
  u'uuid': 1458565349957},
 {u'name': u'Top 10 Portal Easter Eggs (192kbit).m4a',
  u'packageUUID': 1458565380967,
  u'speed': 0,
  u'status': u'Saltat - Falta FFmpeg\u2122',
  u'statusIconKey': u'kc.021c2b76a1e5849ab674b03a3eb573a1',
  u'uuid': 1458565350212},
 {u'eta': 64,
  u'name': u'Top 10 Portal Easter Eggs (BQ).jpg',
  u'packageUUID': 1458565380967,
  u'speed': 915,
  u'status': u'Desc\xe0rrega',
  u'statusIconKey': u'kc.ae26dcaf8e0c02896c69ba8a1968637c',
  u'uuid': 1458565349769}]

### Warning: The data in status it seems to change depending in jdownloader language... because for me it shows **u'Desc\xe0rrega'** which it means Downloading in my language, Catalan. A little weird they did this to be honest..
### Warning: Some parameters for example status or eta don't show if you haven't started the downloads yet.

**Comment by neox387** [comment]
alright

question: how do i get the packageUUID, since downloads.query_links does not take a package name but only packageUUID ?

would be nice if linkgrabber.add_links would return the packageUUID ?

**Comment by mmarquezs** [comment]
> question: how do i get the packageUUID, since downloads.query_links does not take a package name but only packageUUID ?
Good question, the api has a queryPackages function that it should help but the specs doesn't ahve all the info. I Just sent an email to the JDTeam to get more info. 
> would be nice if linkgrabber.add_links would return the packageUUID ?
Yes that might be useful but that's part of the api, right now it doesn't return anything. 

The only working way that i can think that it would work right now it's to use a link as way to get the package. Save one the links that you want to add, add the links, query all links, find the link you saved before in the response and look the packageUUID of this link.
Here I made an example code:
> links = ["https://www.youtube.com/watch?v=Y_8AZdUW5as","https://www.youtube.com/watch?v=UObG75zvjNc"]
jd.get_device("TEST").linkgrabber.add_links([{"autostart":True,"links":",".join(links)}])
[link["packageUUID"] for link in jd.get_device("TEST").downloads.query_links() if link["url"]==unicode(links[0],'utf-8')][0]
But it doesn't work because it seems autostart option doesn't work either... so it might be something wrong with the api,... or my code, but it worked fine before. I will keep looking. 


It wouldn't work if you have more than one package with the same link but that's not usual.

**Comment by neox387** [comment]
Ye I can work around it to get the UID, only thing I really need is the destination folder working.

sucks that parameters aren't always included, they should just do eta = None instead of leaving it off now i have to try, except it :/

**Comment by mmarquezs** [comment]
> Ye I can work around it to get the UID, only thing I really need is the destination folder working.
Just got a response from JDTeam with more info, if you set overwritePackagizerRules to True the destination folder setting works. 
Example:
> jd.get_device("TEST").linkgrabber.add_links([{"links":"https://www.youtube.com/watch?v=8WNwecc-U3Q","destinationFolder":"/home/username/dfsdfdsf/","overwritePackagizerRules":True}])

> sucks that parameters aren't always included, they should just do eta = None instead of leaving it off now i have to try, except it :/
If you want any special feature to be added to my.jdownloader api you can suggest it sending a message to support@jdownloader.org .

**Comment by neox387** [comment]
Ok the overwrite works goodie :+1: 

allmost getting there :) but gonna use downloads.query_packages:
[https://github.com/mirror/jdownloader/blob/master/src/org/jdownloader/api/downloads/v2/PackageQueryStorable.java](url)

sort of like this:
1 query_packages
2 search for package name in ['name']
3 x = ['uuid]
4 query_packages([{"packageUUIDs":[x]}])

**Comment by neox387** [comment]
trying a cleanup but getting bad parameters, should be same for linkgrabber & downloads:

{"url": "/downloadsV2/cleanup", "apiVer": 1, "rid": 1458590538, "params": ["[1458589866269L]", "[]", "DELETE_FINISHED", "REMOVE_LINKS_ONLY", "ALL"]}

tried the second paremeter as None allso.

> ====- cleanup -====
      Parameter: 1 - long[]-linkIds
      Parameter: 2 - long[]-packageIds
      Parameter: 3 - Action-action
      Parameter: 4 - Mode-mode
      Parameter: 5 - SelectionType-selectionType
           Call: /cleanup?long[]1&long[]2&Action1&Mode1&SelectionType1

**Comment by mmarquezs** [comment]
Oh I see I did messed up with the order of linkIds and packagesIds and there was an other bug that I was converting the lists to strings by mistake on the request_api, it should be fixed now. Added the cleanup to Download and fixed this bug. Also i will do query_packages now.

**Comment by neox387** [comment]
Allright nice :)

**Comment by neox387** [comment]
cleanup doesn't work yet still bad parameters, tried both package & link uuid & none

**Comment by mmarquezs** [comment]
That's weird... Are you sure you have the last version? It seems that list are still getting converted to string but in the last version of code it doesn't do this anymore, I just tried it and works fine.

**Comment by neox387** [comment]
crap indeed was using wrong version -.-

but still bad parameter ? trying to delete all here not a specific package:
{"url": "/downloadsV2/cleanup", "apiVer": 1, "rid": 1458661849, "params": [[], [], "DELETE_FINISHED", "REMOVE_LINKS_ONLY", "ALL"]}

got another crappy problem but might be a setting in jdownloader donno, when i add links with same package name but with different location (subfolder in main folder) it creates a new package with same name instead of adding them in 1 :(, meaning a cleanup or querying a package will not be correct as it just created multiple packages with diffrent uuids i guess :/

**Comment by mmarquezs** [comment]
> but still bad parameter ? trying to delete all here not a specific package:
{"url": "/downloadsV2/cleanup", "apiVer": 1, "rid": 1458661849, "params": [[], [], "DELETE_FINISHED", "REMOVE_LINKS_ONLY", "ALL"]}

I have noticed that, I think you must always provide an uuid either a link uuid or package uuid, but I might be wrong. I tried sending null but it says bad parameters too, empty lists also says bad parameters as you have seen.

> got another crappy problem but might be a setting in jdownloader donno, when i add links with same package name but with different location (subfolder in main folder) it creates a new package with same name instead of adding them in 1 :(, meaning a cleanup or querying a package will not be correct as it just created multiple packages with diffrent uuids i guess :/

Let'me understand this, what you say is that you want one package with certain links saving in a subfolder an other links in an other subfolder but the same package? Or I miosunderstood this? 
For example:

Package 1:
   Link1 Folder: C:/1234/
   Link 2 Folder: C:/5678/

As far as i know it can't even be done from jdownloader it self. If you try to change the location  of a link it creates a second package with the link you changed the save location.

**Comment by neox387** [comment]
Yep noticed this, i'm just gonna flatten directory to keep everything in 1 package.

Ok, cleanup works now guess i fuckt more shit up previously :)

**Comment by neox387** [comment]
Could u create a setup.py or something so pip install the Git works?

**Comment by mmarquezs** [comment]
That was the plan but since is pretty much incomplete I didn't do it.  But since I have free time this week I will try to do it tomorrow.

**Comment by neox387** [comment]
Ok, got another weird issue query packages is sometimes returning list with dict so list with [0] having the status, speed etc, but sometimes it just returns a dict directly with the info

So atm working around with try link = link[0]

**Comment by mmarquezs** [comment]
I have been ill, so i didn't do anything, but today I feel better and I made the setup.
You should be available to install using: 

> pip install git+https://github.com/mmarquezs/My.Jdownloader-API-Python-Library.git@develop

or 

> pip install https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/archive/develop.zip

-

> Ok, got another weird issue query packages with specific packageuuid is sometimes returning list with dict so list with [0] having the status, speed etc, but sometimes it just returns a dict directly with the info

That is API's fault so  you should report to them. Also I have tried to reproduce that without any luck. 

> Edit: allso send an email to jdownloader about getting a response like PackageUID when addLinks and why they leave out info in query instead of just returning None for that info like status eta.. 

You can send it yourself if you want, as I said is this address: support@jdownloader.org  or if you prefer you can go here an open a ticket, because when you sent an email it creates a ticket anyway. 
https://support.jdownloader.org/
I can send it if you want but it would be quicker if you do it yourself.

**Comment by neox387** [comment]
No sorry i meant I have send an email :) anyway the responds was: not all fields are returned to save bandwith & query links, create a list of packageuuids, add new links, query again & check difference not rly a nice solution :/ I had send them this piece of code:

well github markup fails here & strips away text format/color so bit hard to read..


`
def get_download_stats_jd(jd, name):
    start_time = time.time()
    count = 0
    gevent.sleep(10)
    tmp = jd.downloads.query_packages() query everything, I can't search for the package cause I don't know what packageUUID it has
    while not len(tmp):                 if the list is empty from downloadsV2/querypackages I wait till the linkgrabber autostarts
        gevent.sleep(5)
        tmp = jd.downloads.query_packages()
        count += 1
        if count == 10:
            return 1
    while not any(link['name'] in name for link in tmp):  If the list is not empty but my package name is not in the list wait  
        gevent.sleep(5)
        tmp = jd.downloads.query_packages()
        count += 1
        if count == 10:
            return 1
`
`
    for link in tmp:
        if link['name'] in name:
            x = str(link['uuid'])     here we finally find the packageUUID & store it in x to use again later         
            while not 'status' in link:  check if the responds has the field status else program will fail on while link['status'] != 'Finished'
                gevent.sleep(5)
                link = jd.downloads.query_packages([{"status": True, "bytesTotal": True, "bytesLoaded": True,
                                                     "speed": True, "eta": True, "packageUUIDs": [x]}])
                try:
                    link = link[0]
                except:
                    pass
                count += 1
                if count == 10:
                    return 1
            while link['status'] != 'Finished':
                try:
                    speed = link['speed']
                except:
                    speed = 0
                if speed == 0:
                    eta = ''
                else:
                    eta = " " + utils.time_human(link['eta'], fmt_short=True)
                progress = round(float(link['bytesLoaded']) * 100 / link["bytesTotal"], 1)
                greenlet.task.update(speed=(utils.sizeof_human(speed) + '/s --- ' + utils.sizeof_human(
                    link['bytesLoaded']) + ' / ' + utils.sizeof_human(link['bytesTotal'])), progress=progress, eta=eta)
                gevent_sleep_time()
                link = jd.downloads.query_packages([{"status": True, "bytesTotal": True, "bytesLoaded": True,
                                                     "speed": True, "eta": True, "packageUUIDs": [x]}])          query with packageuuid, i guess i need to use an event here instead of requery the package to get new stats
                try:
                    link = link[0]        for some weird reason responds is not allways a dict but can be a dict in a list .. this might be the python api package
                except:
                    pass
            # cfg.jd.disconnect()
            if link['status'] == 'Failed':
                return 1
            stop_time = time.time()
            dltime = int(stop_time - start_time)
            greenlet.task.update(dltime=dltime)
            try:
                jd.downloads.cleanup("DELETE_FINISHED", "REMOVE_LINKS_ONLY", "ALL", packages_ids=[x])
            except:
                pass
            return 0
`

**Comment by neox387** [comment]
donno if this is an issue but could u change your requirements.txt to => requests is at 2.9.1 now :)

**Comment by mmarquezs** [comment]
I fixed your comment, now it shows the code with colors,etcc... You have to do to make it work:
 ,,,python
CODE
 ,,,,

I have been trying but I always get a list with a dict so I don't know why you receive directly a dict :S I'm looking  and the only possible thing it could be is when either decoding the response to utf-8 or loading the json something gets messed up... But  i can't think how this could happen and I don't know how to test it. It happens on all your packages or only in certain packages? Maybe you could provide me a DLC of the package ( right click on package -> Other > Create DLC ) or the link or something so I can test it on my client. 

> donno if this is an issue but could u change your requirements.txt to => requests is at 2.9.1 now :)
I removed it. It's an old file it shouldn't be there.

**Comment by neox387** [comment]
ok ill run a lil debug again some links to see the responds sec.

**Comment by neox387** [comment]
ok weird it's always returning a list now, i swear i saw it return a dict a few times before.. i'll just keep my try in there :)

**Comment by neox387** [comment]
Ok well thanks  for the Api using it as as a package now :)
