### ISSUE TITLE
Parameters 

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#4]
Hey, 

This line is causing issues :

params_request+=[str(param).replace("'",'\"').replace("True","true").replace("False","false").replace('None',"null")] 

This needs to not happen on destinationFolder and links parameters else it will fail

**Comment by mmarquezs** [comment]
It would be helpfull if you can you provide an example of destinationfolder that causes issues.

**Comment by neox387** [comment]
The following seems to be working for me:
```python

            for param in params:
                if not isinstance(param,list):
                    for key, value in list(param.items()):
                        if not isinstance(value, list):
                            if not 'destinationFolder' or not 'links' in key:
                                param[key] = str(value).replace("True", "true").replace("False", "false").replace('None', "null")
                    params_request+=[str(param).replace("'", '\"')]
                else:
                    params_request+=[param]
```

BTW if u fix it could you bump the version in setup.py to 1.0.1 or something ?
so pip knows it's a newer version then the currently installed if this works ? :)

**Comment by mmarquezs** [comment]
yeah... more common that I tough :P Well as I said It  was a quick fix to make it works nothing tested :P and since I don't actually use the library for anything I don't notice this stupid things. I just fixed now in a better way (not your code). Commit: 97c9db26cfbb770e43b9a905522e3b1b7f343f0b
I also changed the version and later I will upload a newer version to pypi. 

If everything is alrigth tell me and I will close the issue or I think you can close it yourself.

**Comment by neox387** [comment]
Works thanks for the quick fix ^^
