### ISSUE TITLE
TypeError in status_downloadSpeedLimit from recently disconnected device

### ISSUE THREAD

**Issue by oribafi** [mmarquezs/My.Jdownloader-API-Python-Library#42]
When a device becomes offline recently and [`device.toolbar.status_downloadSpeedLimit`](https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/blob/003a70256ce279e80f913266297e59dd762ade6f/myjdapi/myjdapi.py#L522-L527) is called, it fails with 

```python
  File "/usr/local/lib/python3.8/site-packages/myjdapi/myjdapi.py", line 524, in status_downloadSpeedLimit
    if self.status['limit']:
TypeError: 'bool' object is not subscriptable
```

**Comment by oribafi** [comment]
I would suggest something like this to raise a more specific exception:

```python
def status_downloadSpeedLimit(self):
    self.status = self.get_status()
    if not self.status:
        raise MYJDConnectionException("No connection established\n")
    return self.status["limit"]
```

What do you think of that?

**Comment by mmarquezs** [comment]
That's what happens when you do a library that you end up not using, you miss some obvious things....

Yeah the thing is that until recently there wasn't exceptions, except some case, anyway recently some were added. But in this case it wasn't applied, the main request function simply returns False if it fails to request something, except if the cause is because the api throws an error. Tbh I have to recheck all the code someday it has some strange logic sometimes. 
Anyway in develop I changed that and I applied a commit so if after attempting direct local connections and api connections still fails to obtain a response it throws the MYJDConnectionException.

That should solve your issue, altough I don't discard the possibility that in some other case happens something similar. 
Please check it out on develop.

**Comment by oribafi** [comment]
Thanks for that improved general fix! Yes, that works for me, and the now-specific exception gets even triggered by the other device commands when the device becomes unavailable (which is to be expected imho).

And great thanks in general for still maintaining this library, even though you do not use it much. There are people that do and are happy that it exists.

**Comment by mmarquezs** [comment]
I just triggered a release, it should already be available in pypi.

**Comment by oribafi** [comment]
Wow, thank you! 🚀
