### ISSUE TITLE
How to change jdwonloader setting?

### ISSUE THREAD

**Issue by G47S53** [mmarquezs/My.Jdownloader-API-Python-Library#53]
Hi,

I use your library and it works perfectly.
Good Job !
I am looking to change the speed limit in the jdownloader settings.
that is possible?
what should I use?

Best regards

**Comment by mmarquezs** [comment]
Possible? Yes
Easy? Yes but... you have to know what to send.
This library focuses mainly in providing exactly the same official API but directly with python and with the only thing simplified is the authentication & encryption the rest is just the same as the official API.

In this case the official API has a config API with just three commands list, get and set and that's it. 
The trick is in finding the parameters the API expects to change x setting, this one compared with some others is slightly better due the list command that returns all the config parameters. 

If you use the list function, it will return this massive response that I put on gist, originally I was putting it on pastebin, but pastebin flagged it as offensive for some reason, although I agree with them it's offensive due to how big it is 😆: https://gist.github.com/mmarquezs/b8bc2fa87ac33da392f66a62edee9481

In this case if you want to change the speed limit in general for all downloads the important part of the file is this:

```json
{
  "docs": "Download Speed limit in bytes.",
  "abstractType": "INT",
  "interfaceName": "org.jdownloader.settings.GeneralSettings",
  "type": "int",
  "key": "DownloadSpeedLimit"
},
```

For using it then you would use the config object function set. For example this is me setting the limit to 30 MB/s ( 31457280 bytes ) :

```python
device.config.set('org.jdownloader.settings.GeneralSettings', None, 'DownloadSpeedLimit', 31457280)
```

Also in this case this one config would also apply as it enables/disables the speed limit:

```json
{
  "abstractType": "BOOLEAN",
  "interfaceName": "org.jdownloader.settings.GeneralSettings",
  "type": "boolean",
  "key": "DownloadSpeedLimitEnabled"
},
```

And probably this one too:

```json
{
  "docs": "Remember Speed Limiter enabled/disabled setting after restart. Note: not associated with pause mode.",
  "abstractType": "BOOLEAN",
  "interfaceName": "org.jdownloader.settings.GeneralSettings",
  "type": "boolean",
  "key": "DownloadSpeedLimitRememberedEnabled"
},
```

The set function also supports using a different config file, that is the parameter I did set to None, not sure how it works in JDownloader but I guess if you have some special separate config file or something that might be used for that.

I close the issue, if you still have doubts feel free to reopen.
